version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  server:
    container_name: weekly-planner-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    command: npm run dev
    volumes:
      - ./:/usr/local/apps/server/dev
      - ignore:/usr/local/apps/server/dev/node_modules/
volumes:
  ignore:
